###
# @name login
POST {{url}} HTTP/1.1

{
    "module": "user",
    "action": "login",
    "parameters": {
        "username": "{{username}}",
        "password": "{{password}}"
    }
}

###
@token = {{login.response.body.token}}

###
# @name create
POST {{url}} HTTP/1.1

{
    "module": "skill",
    "action": "update",
    "parameters": {
        "name": "CSS",
    }
}
###
# @name update
POST {{url}} HTTP/1.1

{
    "module": "skill",
    "action": "update",
    "parameters": {
        "token": "{{token}}",
        "name": "CSS-3",
        "_id": 1
    }
}

###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "skill",
    "action": "read",
    "parameters": {
        "token": "{{token}}"
    }
}
